spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db1
    username: root
    password: ${DB_PASSWORD:12345678}
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

