spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: ${DB_PASSWORD:12345678}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8084


