spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: 12345678

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show_sql: true

server:
  port: 8084


